#!/bin/sh

test -r /etc/inetd.conf || exit 0
test -x /usr/sbin/inetd || exit 0

test -f /bin/router_functions && . /bin/router_functions

start() {
 	msgn "Starting inetd: "
	start-stop-daemon --start --quiet --pidfile /var/run/inetd.pid --exec /usr/sbin/inetd && ok || fail
}
stop() {
	msgn "Stopping inetd: "
	start-stop-daemon --stop --quiet --pidfile /var/run/inetd.pid && ok || fail
}
restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

