#!/bin/sh

test -f /bin/router_functions && . /bin/router_functions

msg "Creating some useful devices..."

mknod -m 666 /dev/ttyS0 c 4 64
mknod -m 666 /dev/ttyS1 c 4 65

mknod /dev/watchdog c 10 130

#For PPP usage only
mknod /dev/ppp c 108 0

# For ARLiX system only
for i in 1 2 3 4 5 6 7 8 9 10
 do
  mknod -m 666 /dev/ttyp$i c 3 $i;
  mknod -m 666 /dev/ptyp$i c 2 $i
done

# For BlueTooth only
for i in 0 1 2 3 4 5 6 7 8 9 10
 do
   mknod -m 666 /dev/rfcomm$i c 216 $i;
done

# For USB Sound only         
ln -s /dev/sound/dsp /dev/dsp
