#!/bin/sh

MODPROBE=`which modprobe`
[ -z "$MODPROBE" ] && MODPROBE="insmod"

loadmodule(){
	local file=$1;
	cat $file | grep -v '^#' | while read m; do 
		$MODPROBE $m
	done
}

test -f /bin/router_functions && . /bin/router_functions

msg "Loading modules..."

if [ -r /etc/modules ]; then 
	loadmodule /etc/modules
fi

for f in /etc/modules.d/*; do 
	[ -r $f ] && loadmodule $f
done
