#! /bin/sh

test -f /bin/router_functions && . /bin/router_functions

[ -c /dev/urandom ] || exit 0
#. /etc/default/rcS

case "$1" in
	start|"")
		# Load and then save 512 bytes,
		# which is the size of the entropy pool
		if [ -f /etc/random-seed ]
		then
			msgn "Initializing random number generator... "
			cat /etc/random-seed >/dev/urandom && ok || fail
		fi
		rm -f /etc/random-seed
		umask 077
		msgn "Updating random seed..."
		dd if=/dev/urandom of=/etc/random-seed count=1 \
			>/dev/null 2>&1 && ok || fail
		umask 022
		;;
	stop)
		# Carry a random seed from shut-down to start-up;
		# see documentation in linux/drivers/char/random.c
		msgn "Saving random seed... "
		umask 077
		dd if=/dev/urandom of=/etc/random-seed count=1 \
			>/dev/null 2>&1 && ok || fail
		;;
	*)
		echo "Usage: urandom {start|stop}" >&2
		exit 1
		;;
esac
