#!/bin/sh
#
# Starts udhcpd.
#

umask 077

mkdir -p /var/lib/misc
touch /var/lib/misc/udhcpd.leases

test -f /bin/router_functions && . /bin/router_functions

start() {
	for conf in /etc/udhcpd*.conf; do
        if [ -r "$conf" ]; then
            msgn "Starting udhcpd: with $conf :	"
            /usr/sbin/udhcpd $conf && ok || fail
        fi
	done
}
stop() {
	msgn "Stopping all udhcpd "
	killall udhcpd 2>/dev/null
	ok
}
restart() {
	stop
	start
}

case "$1" in
start)
		start
	;;
  stop)
		stop
	;;
  restart|reload)
		restart
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

