#!/bin/sh

NAME=watchdog
DAEMON=/sbin/watchdog

[ -x $DAEMON ] || exit 0
[ -c /dev/watchdog ] || exit 0

test -f /bin/router_functions && . /bin/router_functions

start() {
 	msgn "Starting $NAME: "
	start-stop-daemon --start --quiet --pidfile /var/run/$NAME.pid --exec $DAEMON -- /dev/watchdog
	ok
}
stop() {
	msgn "Stopping $NAME: "
	start-stop-daemon --stop --quiet --pidfile /var/run/$NAME.pid
	ok
}
restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

