#!/bin/sh

BIN=owftpd
DEFAULT=/etc/default/$BIN
RUN_D=/var/run
PID_F=$RUN_D/$BIN.pid
[ -f $DEFAULT ] && . $DEFAULT

export PATH=/bin:/usr/bin:/sbin:/usr/sbin

if [ -z "$OPTIONS" ]; then
        echo "OPTIONS is missing... Edit your $DEFAULT"
        exit 0
fi

case $1 in
 start)
  [ "$DISABLE" = "1" ] && exit 0
  if [ "$ENABLESTARTUP" != "1" -a "$2" != "force" ]; then
      echo "You have to set ENABLESTARTUP=\"1\" in $DEFAULT"
      exit 0
  fi
  mkdir -p $RUN_D
  $BIN -P $PID_F $OPTIONS
  ;;
 stop)
  [ -f $PID_F ] && kill $(cat $PID_F)
  ;;
 *)
  echo "usage: $0 (start|stop)"
  exit 1
esac

exit $?
