#!/bin/sh

. /etc/templates/lib
[ -z ${ppp_auth_mode} ] && die "ppp_auth_mode is not set"


show_header $0

eval `kdb -q ls sys_auth_*`

echo "# Secrets for authentication using $ppp_auth_mode"
echo "# Client		 Server		 Secret		 IP address"

PPP_SECRETS=`kdb kls sys_auth_ppp_${ppp_auth_mode}*`

for secret in $PPP_SECRETS; do
	eval "export \$$secret"
	[ "x${server}y" = "xy" ] && server="*"
	[ "x${ipaddr}y" = "xy" ] && ipaddr="*"
	echo "$username		 $server		 $password		 $ipaddr "
	unset username server password ipaddr
done


