#!/bin/sh

INSTALL_DIR=../public_html/

cd /home/flyrouter/flyrouter

mkdir -p -v ~/FlyRouterBIN/download
rm -rf ./dl
ln -s ~/FlyRouterBIN/download dl

clean_root(){
	make clean_root
}

clean_linux(){
	rm -rf build_mipsel/linux*
}

clean_build(){
	rm -rf build_mipsel
}

install(){
	mkdir -p $INSTALL_DIR
	cp -a bin $INSTALL_DIR
	rm -f bin/openwrt*
}

build(){
	local ver=$1
	local config=$2
	clean_linux
	temp=`tempfile -p linux -s -config`
	if [ -r target/linux/ar7-$ver/config-$config ]; then
		cp target/linux/ar7-$ver/config $temp
		cp target/linux/ar7-$ver/config-$config target/linux/ar7-$ver/config
	fi
	cp target/linux/ar7-$ver/openwrt-config-$config .config
	make oldconfig DEVELOPER=1
	make --jobs=4 V=99
	#make --jobs=4
	#make
	ret=$?
	if [ "$ret" = 0 ]; then
		rename "s/.bin/-$config.bin/" bin/*
		install 
	fi

	if [ -s $temp ]; then
		cp $temp target/linux/ar7-$ver/config
	fi
	rm $temp
	[ "$ret" != 0 ] && exit 1
}

clean_build
clean_root
build 2.4 midge-tnetd
