#!/bin/sh

INSTALL_DIR=/home/`whoami`/FlyRouterBIN

mkdir -p ${INSTALL_DIR}/download
rm -rf ./dl
ln -s ${INSTALL_DIR}/download dl


clean_root(){
	make root_clean
}

clean_linux(){
	rm -rf build_mipsel/linux*
}

clean_build(){
	rm -rf build_mipsel
}

install(){
	rev=`cat Revision | head -n 1 | awk '/^Revision:/ { print $2 }'`
	#
	mkdir -p $INSTALL_DIR/firmware-mipsel-skyrouter	
	cp -a bin/openwrt-brcm5354-2.4-squashfs.trx $INSTALL_DIR/firmware-mipsel-skyrouter/$1-r${rev}-`date +%Y%m%d%H%M`.trx
	cp -a bin/openwrt-brcm5354-2.4-squashfs.trx $INSTALL_DIR/firmware-mipsel-skyrouter/
	#
	mkdir -p $INSTALL_DIR/packages-mipsel-skyrouter/
	cp -f bin/packages/* $INSTALL_DIR/packages-mipsel-skyrouter/
	#
	rm -rf bin
}

build(){
	local ver=$1
	local config=$2
	export SKY_CONFIG=$2
	clean_build
	clean_root
	temp=`tempfile -p linux -s -config`
	if [ -r target/linux/brcm5354-$ver/config-$config ]; then
		cp target/linux/brcm5354-$ver/config $temp
		cp target/linux/brcm5354-$ver/config-$config target/linux/brcm5354-$ver/config
	fi
	cp target/linux/brcm5354-$ver/system-$config .config
	make oldconfig DEVELOPER=1
	make --jobs=3
	#make --jobs=1 V=99
	ret=$?
	if [ "$ret" = 0 ]; then
		rename "s/.bin/-$config.bin/" bin/*
		install $config
	fi

	if [ -s $temp ]; then
		cp $temp target/linux/brcm5354-$ver/config
	fi
	rm $temp
	[ "$ret" != 0 ] && exit 1
}

upload_firmware() {
       DESTINATION="vu2049@hosting:~/htdocs/downloads/software"
       scp ${INSTALL_DIR}/firmware-mipsel-skyrouter/*.trx $DESTINATION/skyrouter/upgrade/2010-current
}

upload_packages() {
       DESTINATION="vu2049@hosting:~/htdocs/downloads/software"
       scp ${INSTALL_DIR}/packages-mipsel-skyrouter/* $DESTINATION/skyrouter/packages/
}



rm -rf bin build_mipsel
#
#build 2.4 skyrouter-kernel_rd-011_flymac
#build 2.4 skyrouter-kernel_rd-010
#
#build 2.4 skyrouter-universal_rd-010_flyavr
build 2.4 skyrouter-universal_rd-011_flymac
#build 2.4 skyrouter-u2b_rd-011_flymac
#build 2.4 skyrouter-lite_rd-012_flymac
#
#build 2.4 skyrouter-vbox_ovpn_snmp_noweb
#build 2.4 skyrouter-asterisk_lift
#build 2.4 skyrouter-cabine_lift
#build 2.4 skyrouter-voip_all
#time build 2.4 skyrouter-admin
#
#upload_firmware
#upload_packages
