#!/bin/sh
#
# Starts pppoe-relay.
#

test -x /usr/sbin/pppoe-relay || exit 0

case $1 in
 start)
  echo "Warning, pppoe-relay not started"
  sleep 1
  #pppoe-relay -C eth2 -S eth1
  ;;
 *)
  echo "usage: $0 (start)"
  exit 1
esac

exit $?
