#!/bin/sh
#
# FlyRouter Team (c) 2004-2007 | http://www.flyrouter.net
# Get interface statistic script
# Version 0.3a 20070907

(iptables -nvxL ACCOUNT-SRC; iptables -nvxL ACCOUNT-DST) | grep acct-

# For advanced daemon report                                                                                
#while read name; do                                                             
#    (iptables -nvxL ACCOUNT-SRC; iptables -nvxL ACCOUNT-DST) | grep acct-.-$
#done 