#!/bin/sh
# Sigrand SG-17PCI configuration tool 
# for Linux kernel v 2.6
#
#	Written 2007 by Artem U. Polyakov
#
#---------------------------------------------------------

PCI_PATH="/sys/bus/pci/drivers/mr17h"

#---------------------------------------------------------

print_usage()
{
    echo "SIGRAND MR-17H IO window debug tool"
    echo "Usage:"
    echo "  sg16cfg <if> s <addr> <val>     - set register <addr> to <val>"
    echo "  sg16cfg <if> r <addr> <count>   - read <count> bytes starting from <addr>"    
}


#---------------------------------------------------------

# Check that interface name specifyed
if [ $# -lt "4" ]; then
    print_usage
    exit
fi

cdir=`pwd`
iface=$1

if [ -d "$PCI_PATH/$1" ]; then
	cd "$PCI_PATH/$1"
else
	echo "$0: No such device $1"
	exit
fi

case $2 in
    "s")
	echo "$3 $4" > winwrite
	cat winwrite
	echo
	;;
    "r")
	echo "$3 $4" > winread
	cat winread
	;;
    *)
	echo "Bad parameters!"
esac
