/*
 * Automatically generated C config: don't edit
 */
#define AUTOCONF_INCLUDED
#define CONFIG_MIPS 1
#define CONFIG_MIPS32 1
#undef  CONFIG_MIPS64

/*
 * Code maturity level options
 */
#define CONFIG_EXPERIMENTAL 1

/*
 * Loadable module support
 */
#define CONFIG_MODULES 1
#undef  CONFIG_MODVERSIONS
#undef  CONFIG_KMOD

/*
 * Machine selection
 */
#undef  CONFIG_ACER_PICA_61
#undef  CONFIG_MIPS_BOSPORUS
#undef  CONFIG_MIPS_FICMMP
#undef  CONFIG_MIPS_MIRAGE
#undef  CONFIG_MIPS_DB1000
#undef  CONFIG_MIPS_DB1100
#undef  CONFIG_MIPS_DB1500
#undef  CONFIG_MIPS_DB1550
#undef  CONFIG_MIPS_DB1200
#undef  CONFIG_MIPS_PB1000
#undef  CONFIG_MIPS_PB1100
#undef  CONFIG_MIPS_PB1500
#undef  CONFIG_MIPS_PB1550
#undef  CONFIG_MIPS_PB1200
#undef  CONFIG_MIPS_HYDROGEN3
#undef  CONFIG_MIPS_XXS1500
#undef  CONFIG_MIPS_MTX1
#undef  CONFIG_COGENT_CSB250
#undef  CONFIG_BAGET_MIPS
#undef  CONFIG_CASIO_E55
#undef  CONFIG_MIPS_COBALT
#undef  CONFIG_DECSTATION
#undef  CONFIG_MIPS_EV64120
#undef  CONFIG_MIPS_EV96100
#undef  CONFIG_MIPS_IVR
#undef  CONFIG_HP_LASERJET
#undef  CONFIG_IBM_WORKPAD
#undef  CONFIG_LASAT
#undef  CONFIG_MIPS_ITE8172
#undef  CONFIG_MIPS_ATLAS
#undef  CONFIG_MIPS_MAGNUM_4000
#undef  CONFIG_MIPS_MALTA
#undef  CONFIG_MIPS_SEAD
#undef  CONFIG_MOMENCO_OCELOT
#undef  CONFIG_MOMENCO_OCELOT_G
#undef  CONFIG_MOMENCO_OCELOT_C
#undef  CONFIG_MOMENCO_JAGUAR_ATX
#undef  CONFIG_PMC_BIG_SUR
#undef  CONFIG_PMC_STRETCH
#undef  CONFIG_PMC_YOSEMITE
#undef  CONFIG_DDB5074
#undef  CONFIG_DDB5476
#undef  CONFIG_DDB5477
#undef  CONFIG_NEC_OSPREY
#undef  CONFIG_NEC_EAGLE
#undef  CONFIG_OLIVETTI_M700
#undef  CONFIG_NINO
#undef  CONFIG_SGI_IP22
#undef  CONFIG_SGI_IP27
#undef  CONFIG_SIBYTE_SB1xxx_SOC
#define CONFIG_MIPS_BRCM 1
#define CONFIG_BCM947XX 1
#define CONFIG_BCM4710 1
#define CONFIG_BCM4310 1
#define CONFIG_BCM4704 1
#define CONFIG_BCM5365 1
#undef  CONFIG_SNI_RM200_PCI
#undef  CONFIG_TANBAC_TB0226
#undef  CONFIG_TANBAC_TB0229
#undef  CONFIG_TOSHIBA_JMR3927
#undef  CONFIG_TOSHIBA_RBTX4927
#undef  CONFIG_VICTOR_MPC30X
#undef  CONFIG_ZAO_CAPCELLA
#undef  CONFIG_HIGHMEM
#define CONFIG_RWSEM_GENERIC_SPINLOCK 1
#undef  CONFIG_RWSEM_XCHGADD_ALGORITHM
#define CONFIG_CMDLINE "root=/dev/mtdblock2 rootfstype=squashfs,jffs2 init=/etc/preinit noinitrd console=ttyS0,115200"
#define CONFIG_PCI 1
#define CONFIG_NONCOHERENT_IO 1
#define CONFIG_NEW_TIME_C 1
#define CONFIG_NEW_IRQ 1
#define CONFIG_HND 1
#undef  CONFIG_MIPS_AU1000

/*
 * CPU selection
 */
#define CONFIG_CPU_MIPS32 1
#undef  CONFIG_CPU_MIPS64
#undef  CONFIG_CPU_R3000
#undef  CONFIG_CPU_TX39XX
#undef  CONFIG_CPU_VR41XX
#undef  CONFIG_CPU_R4300
#undef  CONFIG_CPU_R4X00
#undef  CONFIG_CPU_TX49XX
#undef  CONFIG_CPU_R5000
#undef  CONFIG_CPU_R5432
#undef  CONFIG_CPU_R6000
#undef  CONFIG_CPU_NEVADA
#undef  CONFIG_CPU_R8000
#undef  CONFIG_CPU_R10000
#undef  CONFIG_CPU_RM7000
#undef  CONFIG_CPU_RM9000
#undef  CONFIG_CPU_SB1
#define CONFIG_PAGE_SIZE_4KB 1
#undef  CONFIG_PAGE_SIZE_16KB
#undef  CONFIG_PAGE_SIZE_64KB
#define CONFIG_CPU_HAS_PREFETCH 1
#undef  CONFIG_VTAG_ICACHE
#undef  CONFIG_64BIT_PHYS_ADDR
#undef  CONFIG_CPU_ADVANCED
#define CONFIG_CPU_HAS_LLSC 1
#undef  CONFIG_CPU_HAS_LLDSCD
#undef  CONFIG_CPU_HAS_WB
#define CONFIG_CPU_HAS_SYNC 1

/*
 * General setup
 */
#define CONFIG_CPU_LITTLE_ENDIAN 1
#undef  CONFIG_BUILD_ELF64
#define CONFIG_NET 1
#define CONFIG_PCI 1
#undef  CONFIG_PCI_NEW
#define CONFIG_PCI_AUTO 1
#undef  CONFIG_PCI_NAMES
#undef  CONFIG_ISA
#undef  CONFIG_TC
#undef  CONFIG_MCA
#undef  CONFIG_SBUS
#define CONFIG_HOTPLUG 1

/*
 * PCMCIA/CardBus support
 */
#undef  CONFIG_PCMCIA
#define CONFIG_PCMCIA_MODULE 1
#define CONFIG_CARDBUS 1
#undef  CONFIG_TCIC
#undef  CONFIG_I82092
#undef  CONFIG_I82365

/*
 * PCI Hotplug Support
 */
#undef  CONFIG_HOTPLUG_PCI
#undef  CONFIG_HOTPLUG_PCI_COMPAQ
#undef  CONFIG_HOTPLUG_PCI_COMPAQ_NVRAM
#undef  CONFIG_HOTPLUG_PCI_SHPC
#undef  CONFIG_HOTPLUG_PCI_SHPC_POLL_EVENT_MODE
#undef  CONFIG_HOTPLUG_PCI_PCIE
#undef  CONFIG_HOTPLUG_PCI_PCIE_POLL_EVENT_MODE
#define CONFIG_SYSVIPC 1
#undef  CONFIG_BSD_PROCESS_ACCT
#define CONFIG_SYSCTL 1
#define CONFIG_KCORE_ELF 1
#undef  CONFIG_KCORE_AOUT
#undef  CONFIG_BINFMT_AOUT
#define CONFIG_BINFMT_ELF 1
#undef  CONFIG_BINFMT_ELF_AOUT
#undef  CONFIG_MIPS32_COMPAT
#undef  CONFIG_MIPS32_O32
#undef  CONFIG_MIPS32_N32
#undef  CONFIG_BINFMT_ELF32
#undef  CONFIG_BINFMT_MISC
#undef  CONFIG_OOM_KILLER
#undef  CONFIG_CMDLINE_BOOL

/*
 * Memory Technology Devices (MTD)
 */
#define CONFIG_MTD 1
#undef  CONFIG_MTD_DEBUG
#define CONFIG_MTD_PARTITIONS 1
#undef  CONFIG_MTD_CONCAT
#undef  CONFIG_MTD_REDBOOT_PARTS
#undef  CONFIG_MTD_CMDLINE_PARTS

/*
 * User Modules And Translation Layers
 */
#define CONFIG_MTD_CHAR 1
#define CONFIG_MTD_BLOCK 1
#undef  CONFIG_FTL
#undef  CONFIG_NFTL

/*
 * RAM/ROM/Flash chip drivers
 */
#define CONFIG_MTD_CFI 1
#undef  CONFIG_MTD_JEDECPROBE
#define CONFIG_MTD_GEN_PROBE 1
#define CONFIG_MTD_CFI_ADV_OPTIONS 1
#define CONFIG_MTD_CFI_NOSWAP 1
#undef  CONFIG_MTD_CFI_BE_BYTE_SWAP
#undef  CONFIG_MTD_CFI_LE_BYTE_SWAP
#define CONFIG_MTD_CFI_GEOMETRY 1
#undef  CONFIG_MTD_CFI_B1
#define CONFIG_MTD_CFI_B2 1
#undef  CONFIG_MTD_CFI_B4
#undef  CONFIG_MTD_CFI_B8
#define CONFIG_MTD_CFI_I1 1
#undef  CONFIG_MTD_CFI_I2
#undef  CONFIG_MTD_CFI_I4
#undef  CONFIG_MTD_CFI_I8
#define CONFIG_MTD_CFI_INTELEXT 1
#define CONFIG_MTD_CFI_AMDSTD 1
#undef  CONFIG_MTD_CFI_STAA
#define CONFIG_MTD_CFI_SSTSTD 1
#undef  CONFIG_MTD_RAM
#undef  CONFIG_MTD_ROM
#undef  CONFIG_MTD_ABSENT
#undef  CONFIG_MTD_OBSOLETE_CHIPS
#undef  CONFIG_MTD_AMDSTD
#undef  CONFIG_MTD_SHARP
#undef  CONFIG_MTD_JEDEC

/*
 * Mapping drivers for chip access
 */
#undef  CONFIG_MTD_PHYSMAP
#define CONFIG_MTD_BCM947XX 1
#undef  CONFIG_MTD_PB1000
#undef  CONFIG_MTD_PB1500
#undef  CONFIG_MTD_PB1100
#undef  CONFIG_MTD_BOSPORUS
#undef  CONFIG_MTD_XXS1500
#undef  CONFIG_MTD_MTX1
#undef  CONFIG_MTD_DB1X00
#undef  CONFIG_MTD_PB1550
#undef  CONFIG_MTD_HYDROGEN3
#undef  CONFIG_MTD_MIRAGE
#undef  CONFIG_MTD_CSTM_MIPS_IXX
#undef  CONFIG_MTD_OCELOT
#undef  CONFIG_MTD_LASAT
#undef  CONFIG_MTD_PCI
#undef  CONFIG_MTD_PCMCIA

/*
 * Self-contained MTD device drivers
 */
#undef  CONFIG_MTD_PMC551
#undef  CONFIG_MTD_SLRAM
#undef  CONFIG_MTD_MTDRAM
#undef  CONFIG_MTD_BLKMTD

/*
 * Disk-On-Chip Device Drivers
 */
#undef  CONFIG_MTD_DOC1000
#undef  CONFIG_MTD_DOC2000
#undef  CONFIG_MTD_DOC2001
#undef  CONFIG_MTD_DOCPROBE

/*
 * NAND Flash Device Drivers
 */
#undef  CONFIG_MTD_NAND

/*
 * Parallel port support
 */
#undef  CONFIG_PARPORT
#define CONFIG_PARPORT_MODULE 1
#undef  CONFIG_PARPORT_PC
#undef  CONFIG_PARPORT_SPLINK
#define CONFIG_PARPORT_SPLINK_MODULE 1
#undef  CONFIG_PARPORT_AMIGA
#undef  CONFIG_PARPORT_MFC3
#undef  CONFIG_PARPORT_ATARI
#undef  CONFIG_PARPORT_GSC
#undef  CONFIG_PARPORT_SUNBPP
#undef  CONFIG_PARPORT_IP22
#undef  CONFIG_PARPORT_OTHER
#undef  CONFIG_PARPORT_1284

/*
 * Plug and Play configuration
 */
#undef  CONFIG_PNP
#undef  CONFIG_ISAPNP

/*
 * Block devices
 */
#undef  CONFIG_BLK_DEV_FD
#undef  CONFIG_BLK_DEV_XD
#undef  CONFIG_PARIDE
#undef  CONFIG_BLK_CPQ_DA
#undef  CONFIG_BLK_CPQ_CISS_DA
#undef  CONFIG_CISS_SCSI_TAPE
#undef  CONFIG_CISS_MONITOR_THREAD
#undef  CONFIG_BLK_DEV_DAC960
#undef  CONFIG_BLK_DEV_UMEM
#undef  CONFIG_BLK_DEV_SX8
#undef  CONFIG_BLK_DEV_LOOP
#define CONFIG_BLK_DEV_LOOP_MODULE 1
#undef  CONFIG_BLK_DEV_NBD
#define CONFIG_BLK_DEV_NBD_MODULE 1
#undef  CONFIG_BLK_DEV_RAM
#undef  CONFIG_BLK_DEV_INITRD
#undef  CONFIG_BLK_STATS

/*
 * Multi-device support (RAID and LVM)
 */
#undef  CONFIG_MD
#undef  CONFIG_BLK_DEV_MD
#undef  CONFIG_MD_LINEAR
#undef  CONFIG_MD_RAID0
#undef  CONFIG_MD_RAID1
#undef  CONFIG_MD_RAID5
#undef  CONFIG_MD_MULTIPATH
#undef  CONFIG_BLK_DEV_LVM

/*
 * Networking options
 */
#define CONFIG_PACKET 1
#define CONFIG_PACKET_MMAP 1
#undef  CONFIG_NETLINK_DEV
#define CONFIG_NETLINK_DEV_MODULE 1
#define CONFIG_NETFILTER 1
#undef  CONFIG_NETFILTER_DEBUG
#define CONFIG_FILTER 1
#define CONFIG_UNIX 1
#define CONFIG_INET 1
#define CONFIG_IP_MULTICAST 1
#define CONFIG_IP_ADVANCED_ROUTER 1
#define CONFIG_IP_MULTIPLE_TABLES 1
#define CONFIG_IP_ROUTE_FWMARK 1
#define CONFIG_IP_ROUTE_NAT 1
#define CONFIG_IP_ROUTE_MULTIPATH 1
#define CONFIG_IP_ROUTE_TOS 1
#undef  CONFIG_IP_ROUTE_VERBOSE
#undef  CONFIG_IP_PNP
#undef  CONFIG_NET_IPIP
#define CONFIG_NET_IPIP_MODULE 1
#undef  CONFIG_NET_IPGRE
#define CONFIG_NET_IPGRE_MODULE 1
#undef  CONFIG_NET_IPGRE_BROADCAST
#undef  CONFIG_IP_MROUTE
#undef  CONFIG_ARPD
#undef  CONFIG_INET_ECN
#undef  CONFIG_SYN_COOKIES

/*
 *   IP: Netfilter Configuration
 */
#define CONFIG_IP_NF_CONNTRACK 1
#define CONFIG_IP_NF_CONNTRACK_MARK 1
#define CONFIG_IP_NF_FTP 1
#undef  CONFIG_IP_NF_AMANDA
#define CONFIG_IP_NF_AMANDA_MODULE 1
#undef  CONFIG_IP_NF_TFTP
#define CONFIG_IP_NF_TFTP_MODULE 1
#define CONFIG_IP_NF_IRC 1
#undef  CONFIG_IP_NF_CT_ACCT
#define CONFIG_IP_NF_CT_ACCT_MODULE 1
#undef  CONFIG_IP_NF_MATCH_CONNBYTES
#define CONFIG_IP_NF_MATCH_CONNBYTES_MODULE 1
#undef  CONFIG_IP_NF_CT_PROTO_GRE
#define CONFIG_IP_NF_CT_PROTO_GRE_MODULE 1
#undef  CONFIG_IP_NF_PPTP
#define CONFIG_IP_NF_PPTP_MODULE 1
#undef  CONFIG_IP_NF_H323
#define CONFIG_IP_NF_H323_MODULE 1
#undef  CONFIG_IP_NF_RTSP
#define CONFIG_IP_NF_RTSP_MODULE 1
#undef  CONFIG_IP_NF_MMS
#define CONFIG_IP_NF_MMS_MODULE 1
#undef  CONFIG_IP_NF_QUEUE
#define CONFIG_IP_NF_QUEUE_MODULE 1
#define CONFIG_IP_NF_IPTABLES 1
#undef  CONFIG_IP_NF_MATCH_LIMIT
#define CONFIG_IP_NF_MATCH_LIMIT_MODULE 1
#undef  CONFIG_IP_NF_MATCH_QUOTA
#define CONFIG_IP_NF_MATCH_QUOTA_MODULE 1
#undef  CONFIG_IP_NF_SET
#define CONFIG_IP_NF_SET_MODULE 1
#define CONFIG_IP_NF_SET_MAX (256)
#define CONFIG_IP_NF_SET_HASHSIZE (1024)
#undef  CONFIG_IP_NF_MATCH_SET
#define CONFIG_IP_NF_MATCH_SET_MODULE 1
#undef  CONFIG_IP_NF_TARGET_SET
#define CONFIG_IP_NF_TARGET_SET_MODULE 1
#undef  CONFIG_IP_NF_SET_IPMAP
#define CONFIG_IP_NF_SET_IPMAP_MODULE 1
#undef  CONFIG_IP_NF_SET_PORTMAP
#define CONFIG_IP_NF_SET_PORTMAP_MODULE 1
#undef  CONFIG_IP_NF_SET_MACIPMAP
#define CONFIG_IP_NF_SET_MACIPMAP_MODULE 1
#undef  CONFIG_IP_NF_SET_IPHASH
#define CONFIG_IP_NF_SET_IPHASH_MODULE 1
#undef  CONFIG_IP_NF_SET_NETHASH
#define CONFIG_IP_NF_SET_NETHASH_MODULE 1
#undef  CONFIG_IP_NF_SET_IPTREE
#define CONFIG_IP_NF_SET_IPTREE_MODULE 1
#undef  CONFIG_IP_NF_MATCH_MAC
#define CONFIG_IP_NF_MATCH_MAC_MODULE 1
#undef  CONFIG_IP_NF_MATCH_PKTTYPE
#define CONFIG_IP_NF_MATCH_PKTTYPE_MODULE 1
#define CONFIG_IP_NF_MATCH_MARK 1
#define CONFIG_IP_NF_MATCH_MULTIPORT 1
#undef  CONFIG_IP_NF_MATCH_TOS
#define CONFIG_IP_NF_MATCH_TOS_MODULE 1
#undef  CONFIG_IP_NF_MATCH_TIME
#define CONFIG_IP_NF_MATCH_TIME_MODULE 1
#undef  CONFIG_IP_NF_MATCH_CONDITION
#define CONFIG_IP_NF_MATCH_CONDITION_MODULE 1
#undef  CONFIG_IP_NF_MATCH_RECENT
#define CONFIG_IP_NF_MATCH_RECENT_MODULE 1
#undef  CONFIG_IP_NF_MATCH_ECN
#define CONFIG_IP_NF_MATCH_ECN_MODULE 1
#undef  CONFIG_IP_NF_MATCH_IPP2P
#define CONFIG_IP_NF_MATCH_IPP2P_MODULE 1
#undef  CONFIG_IP_NF_MATCH_DSCP
#define CONFIG_IP_NF_MATCH_DSCP_MODULE 1
#undef  CONFIG_IP_NF_MATCH_AH_ESP
#define CONFIG_IP_NF_MATCH_AH_ESP_MODULE 1
#undef  CONFIG_IP_NF_MATCH_LENGTH
#define CONFIG_IP_NF_MATCH_LENGTH_MODULE 1
#undef  CONFIG_IP_NF_MATCH_TTL
#define CONFIG_IP_NF_MATCH_TTL_MODULE 1
#undef  CONFIG_IP_NF_MATCH_TCPMSS
#define CONFIG_IP_NF_MATCH_TCPMSS_MODULE 1
#undef  CONFIG_IP_NF_MATCH_HELPER
#define CONFIG_IP_NF_MATCH_HELPER_MODULE 1
#define CONFIG_IP_NF_MATCH_STATE 1
#undef  CONFIG_IP_NF_MATCH_CONNTRACK
#define CONFIG_IP_NF_MATCH_CONNTRACK_MODULE 1
#undef  CONFIG_IP_NF_MATCH_CONNMARK
#define CONFIG_IP_NF_MATCH_CONNMARK_MODULE 1
#undef  CONFIG_IP_NF_MATCH_UNCLEAN
#define CONFIG_IP_NF_MATCH_UNCLEAN_MODULE 1
#undef  CONFIG_IP_NF_MATCH_STRING
#define CONFIG_IP_NF_MATCH_STRING_MODULE 1
#undef  CONFIG_IP_NF_MATCH_OWNER
#define CONFIG_IP_NF_MATCH_OWNER_MODULE 1
#undef  CONFIG_IP_NF_MATCH_LAYER7
#define CONFIG_IP_NF_MATCH_LAYER7_MODULE 1
#undef  CONFIG_IP_NF_MATCH_LAYER7_DEBUG
#define CONFIG_IP_NF_FILTER 1
#define CONFIG_IP_NF_TARGET_REJECT 1
#undef  CONFIG_IP_NF_TARGET_MIRROR
#define CONFIG_IP_NF_TARGET_MIRROR_MODULE 1
#define CONFIG_IP_NF_NAT 1
#define CONFIG_IP_NF_NAT_NEEDED 1
#define CONFIG_IP_NF_TARGET_MASQUERADE 1
#undef  CONFIG_IP_NF_TARGET_REDIRECT
#define CONFIG_IP_NF_TARGET_REDIRECT_MODULE 1
#undef  CONFIG_IP_NF_TARGET_NETMAP
#define CONFIG_IP_NF_TARGET_NETMAP_MODULE 1
#undef  CONFIG_IP_NF_NAT_PPTP
#define CONFIG_IP_NF_NAT_PPTP_MODULE 1
#undef  CONFIG_IP_NF_NAT_PROTO_GRE
#define CONFIG_IP_NF_NAT_PROTO_GRE_MODULE 1
#undef  CONFIG_IP_NF_NAT_AMANDA
#define CONFIG_IP_NF_NAT_AMANDA_MODULE 1
#undef  CONFIG_IP_NF_NAT_H323
#define CONFIG_IP_NF_NAT_H323_MODULE 1
#undef  CONFIG_IP_NF_NAT_RTSP
#define CONFIG_IP_NF_NAT_RTSP_MODULE 1
#undef  CONFIG_IP_NF_NAT_MMS
#define CONFIG_IP_NF_NAT_MMS_MODULE 1
#undef  CONFIG_IP_NF_NAT_SNMP_BASIC
#define CONFIG_IP_NF_NAT_SNMP_BASIC_MODULE 1
#define CONFIG_IP_NF_NAT_IRC 1
#define CONFIG_IP_NF_NAT_FTP 1
#undef  CONFIG_IP_NF_NAT_TFTP
#define CONFIG_IP_NF_NAT_TFTP_MODULE 1
#define CONFIG_IP_NF_MANGLE 1
#undef  CONFIG_IP_NF_TARGET_TOS
#define CONFIG_IP_NF_TARGET_TOS_MODULE 1
#undef  CONFIG_IP_NF_TARGET_ECN
#define CONFIG_IP_NF_TARGET_ECN_MODULE 1
#undef  CONFIG_IP_NF_TARGET_DSCP
#define CONFIG_IP_NF_TARGET_DSCP_MODULE 1
#define CONFIG_IP_NF_TARGET_MARK 1
#undef  CONFIG_IP_NF_TARGET_IMQ
#define CONFIG_IP_NF_TARGET_IMQ_MODULE 1
#undef  CONFIG_IP_NF_TARGET_CONNMARK
#define CONFIG_IP_NF_TARGET_CONNMARK_MODULE 1
#undef  CONFIG_IP_NF_TARGET_LOG
#define CONFIG_IP_NF_TARGET_LOG_MODULE 1
#undef  CONFIG_IP_NF_TARGET_TTL
#define CONFIG_IP_NF_TARGET_TTL_MODULE 1
#undef  CONFIG_IP_NF_TARGET_ULOG
#define CONFIG_IP_NF_TARGET_ULOG_MODULE 1
#define CONFIG_IP_NF_TARGET_TCPMSS 1
#undef  CONFIG_IP_NF_ARPTABLES
#define CONFIG_IP_NF_ARPTABLES_MODULE 1
#undef  CONFIG_IP_NF_ARPFILTER
#define CONFIG_IP_NF_ARPFILTER_MODULE 1
#undef  CONFIG_IP_NF_ARP_MANGLE
#define CONFIG_IP_NF_ARP_MANGLE_MODULE 1

/*
 *   IP: Virtual Server Configuration
 */
#undef  CONFIG_IP_VS
#define CONFIG_IP_VS_MODULE 1
#undef  CONFIG_IP_VS_DEBUG
#define CONFIG_IP_VS_TAB_BITS (12)

/*
 * IPVS scheduler
 */
#undef  CONFIG_IP_VS_RR
#define CONFIG_IP_VS_RR_MODULE 1
#undef  CONFIG_IP_VS_WRR
#define CONFIG_IP_VS_WRR_MODULE 1
#undef  CONFIG_IP_VS_LC
#define CONFIG_IP_VS_LC_MODULE 1
#undef  CONFIG_IP_VS_WLC
#define CONFIG_IP_VS_WLC_MODULE 1
#undef  CONFIG_IP_VS_LBLC
#define CONFIG_IP_VS_LBLC_MODULE 1
#undef  CONFIG_IP_VS_LBLCR
#define CONFIG_IP_VS_LBLCR_MODULE 1
#undef  CONFIG_IP_VS_DH
#define CONFIG_IP_VS_DH_MODULE 1
#undef  CONFIG_IP_VS_SH
#define CONFIG_IP_VS_SH_MODULE 1
#undef  CONFIG_IP_VS_SED
#define CONFIG_IP_VS_SED_MODULE 1
#undef  CONFIG_IP_VS_NQ
#define CONFIG_IP_VS_NQ_MODULE 1

/*
 * IPVS application helper
 */
#undef  CONFIG_IP_VS_FTP
#define CONFIG_IP_VS_FTP_MODULE 1
#undef  CONFIG_IPV6
#define CONFIG_IPV6_MODULE 1

/*
 *   IPv6: Netfilter Configuration
 */
#undef  CONFIG_IP6_NF_QUEUE
#define CONFIG_IP6_NF_QUEUE_MODULE 1
#undef  CONFIG_IP6_NF_IPTABLES
#define CONFIG_IP6_NF_IPTABLES_MODULE 1
#undef  CONFIG_IP6_NF_MATCH_LIMIT
#define CONFIG_IP6_NF_MATCH_LIMIT_MODULE 1
#undef  CONFIG_IP6_NF_MATCH_CONDITION
#define CONFIG_IP6_NF_MATCH_CONDITION_MODULE 1
#undef  CONFIG_IP6_NF_MATCH_MAC
#define CONFIG_IP6_NF_MATCH_MAC_MODULE 1
#undef  CONFIG_IP6_NF_MATCH_RT
#undef  CONFIG_IP6_NF_MATCH_OPTS
#undef  CONFIG_IP6_NF_MATCH_FRAG
#undef  CONFIG_IP6_NF_MATCH_HL
#undef  CONFIG_IP6_NF_MATCH_MULTIPORT
#define CONFIG_IP6_NF_MATCH_MULTIPORT_MODULE 1
#undef  CONFIG_IP6_NF_MATCH_OWNER
#define CONFIG_IP6_NF_MATCH_OWNER_MODULE 1
#undef  CONFIG_IP6_NF_MATCH_MARK
#define CONFIG_IP6_NF_MATCH_MARK_MODULE 1
#undef  CONFIG_IP6_NF_MATCH_IPV6HEADER
#undef  CONFIG_IP6_NF_MATCH_AHESP
#undef  CONFIG_IP6_NF_MATCH_LENGTH
#define CONFIG_IP6_NF_MATCH_LENGTH_MODULE 1
#undef  CONFIG_IP6_NF_MATCH_EUI64
#define CONFIG_IP6_NF_MATCH_EUI64_MODULE 1
#undef  CONFIG_IP6_NF_FILTER
#define CONFIG_IP6_NF_FILTER_MODULE 1
#undef  CONFIG_IP6_NF_TARGET_LOG
#define CONFIG_IP6_NF_TARGET_LOG_MODULE 1
#undef  CONFIG_IP6_NF_MANGLE
#define CONFIG_IP6_NF_MANGLE_MODULE 1
#undef  CONFIG_IP6_NF_TARGET_MARK
#define CONFIG_IP6_NF_TARGET_MARK_MODULE 1
#undef  CONFIG_IP6_NF_TARGET_IMQ
#define CONFIG_IP6_NF_TARGET_IMQ_MODULE 1
#undef  CONFIG_KHTTPD

/*
 *    SCTP Configuration (EXPERIMENTAL)
 */
#undef  CONFIG_IP_SCTP
#undef  CONFIG_ATM
#define CONFIG_VLAN_8021Q 1

/*
 *  
 */
#undef  CONFIG_IPX
#undef  CONFIG_ATALK
#undef  CONFIG_DECNET
#define CONFIG_BRIDGE 1
#undef  CONFIG_X25
#undef  CONFIG_LAPB
#undef  CONFIG_LLC
#undef  CONFIG_NET_DIVERT
#undef  CONFIG_ECONET
#undef  CONFIG_WAN_ROUTER
#define CONFIG_WAN_ROUTER_MODULE 1
#undef  CONFIG_NET_FASTROUTE
#undef  CONFIG_NET_HW_FLOWCONTROL

/*
 * QoS and/or fair queueing
 */
#define CONFIG_NET_SCHED 1
#undef  CONFIG_NET_SCH_CBQ
#define CONFIG_NET_SCH_CBQ_MODULE 1
#undef  CONFIG_NET_SCH_HTB
#define CONFIG_NET_SCH_HTB_MODULE 1
#undef  CONFIG_NET_SCH_CSZ
#define CONFIG_NET_SCH_CSZ_MODULE 1
#undef  CONFIG_NET_SCH_HFSC
#define CONFIG_NET_SCH_HFSC_MODULE 1
#undef  CONFIG_NET_SCH_PRIO
#define CONFIG_NET_SCH_PRIO_MODULE 1
#undef  CONFIG_NET_SCH_RED
#define CONFIG_NET_SCH_RED_MODULE 1
#undef  CONFIG_NET_SCH_SFQ
#define CONFIG_NET_SCH_SFQ_MODULE 1
#undef  CONFIG_NET_SCH_TEQL
#define CONFIG_NET_SCH_TEQL_MODULE 1
#undef  CONFIG_NET_SCH_TBF
#define CONFIG_NET_SCH_TBF_MODULE 1
#undef  CONFIG_NET_SCH_GRED
#define CONFIG_NET_SCH_GRED_MODULE 1
#undef  CONFIG_NET_SCH_NETEM
#undef  CONFIG_NET_SCH_DSMARK
#define CONFIG_NET_SCH_DSMARK_MODULE 1
#undef  CONFIG_NET_SCH_INGRESS
#define CONFIG_NET_SCH_INGRESS_MODULE 1
#define CONFIG_NET_QOS 1
#define CONFIG_NET_ESTIMATOR 1
#define CONFIG_NET_CLS 1
#undef  CONFIG_NET_CLS_TCINDEX
#define CONFIG_NET_CLS_TCINDEX_MODULE 1
#undef  CONFIG_NET_CLS_ROUTE4
#define CONFIG_NET_CLS_ROUTE4_MODULE 1
#define CONFIG_NET_CLS_ROUTE 1
#undef  CONFIG_NET_CLS_FW
#define CONFIG_NET_CLS_FW_MODULE 1
#undef  CONFIG_NET_CLS_U32
#define CONFIG_NET_CLS_U32_MODULE 1
#undef  CONFIG_NET_CLS_RSVP
#define CONFIG_NET_CLS_RSVP_MODULE 1
#undef  CONFIG_NET_CLS_RSVP6
#define CONFIG_NET_CLS_RSVP6_MODULE 1
#define CONFIG_NET_CLS_POLICE 1

/*
 * Network testing
 */
#undef  CONFIG_NET_PKTGEN
#define CONFIG_IPSEC_NAT_TRAVERSAL 1

/*
 * Telephony Support
 */
#undef  CONFIG_PHONE
#undef  CONFIG_PHONE_IXJ
#undef  CONFIG_PHONE_IXJ_PCMCIA

/*
 * ATA/IDE/MFM/RLL support
 */
#undef  CONFIG_IDE
#define CONFIG_IDE_MODULE 1

/*
 * IDE, ATA and ATAPI Block devices
 */
#undef  CONFIG_BLK_DEV_IDE
#define CONFIG_BLK_DEV_IDE_MODULE 1

/*
 * Please see Documentation/ide.txt for help/info on IDE drives
 */
#undef  CONFIG_BLK_DEV_HD_IDE
#undef  CONFIG_BLK_DEV_HD
#undef  CONFIG_BLK_DEV_IDE_SATA
#undef  CONFIG_BLK_DEV_IDEDISK
#define CONFIG_BLK_DEV_IDEDISK_MODULE 1
#undef  CONFIG_IDEDISK_MULTI_MODE
#define CONFIG_IDEDISK_STROKE 1
#undef  CONFIG_BLK_DEV_IDECS
#undef  CONFIG_BLK_DEV_DELKIN
#undef  CONFIG_BLK_DEV_IDECD
#undef  CONFIG_BLK_DEV_IDETAPE
#undef  CONFIG_BLK_DEV_IDEFLOPPY
#undef  CONFIG_BLK_DEV_IDESCSI
#undef  CONFIG_IDE_TASK_IOCTL

/*
 * IDE chipset support/bugfixes
 */
#undef  CONFIG_BLK_DEV_CMD640
#undef  CONFIG_BLK_DEV_CMD640_ENHANCED
#undef  CONFIG_BLK_DEV_ISAPNP
#define CONFIG_BLK_DEV_IDEPCI 1
#undef  CONFIG_BLK_DEV_GENERIC
#undef  CONFIG_IDEPCI_SHARE_IRQ
#define CONFIG_BLK_DEV_IDEDMA_PCI 1
#define CONFIG_BLK_DEV_OFFBOARD 1
#undef  CONFIG_BLK_DEV_IDEDMA_FORCED
#define CONFIG_IDEDMA_PCI_AUTO 1
#undef  CONFIG_IDEDMA_ONLYDISK
#define CONFIG_BLK_DEV_IDEDMA 1
#undef  CONFIG_IDEDMA_PCI_WIP
#undef  CONFIG_BLK_DEV_ADMA100
#undef  CONFIG_BLK_DEV_AEC62XX
#undef  CONFIG_BLK_DEV_ALI15X3
#undef  CONFIG_WDC_ALI15X3
#undef  CONFIG_BLK_DEV_AMD74XX
#undef  CONFIG_AMD74XX_OVERRIDE
#undef  CONFIG_BLK_DEV_ATIIXP
#undef  CONFIG_BLK_DEV_CMD64X
#undef  CONFIG_BLK_DEV_TRIFLEX
#undef  CONFIG_BLK_DEV_CY82C693
#undef  CONFIG_BLK_DEV_CS5530
#undef  CONFIG_BLK_DEV_HPT34X
#undef  CONFIG_HPT34X_AUTODMA
#undef  CONFIG_BLK_DEV_HPT366
#undef  CONFIG_BLK_DEV_PIIX
#undef  CONFIG_BLK_DEV_NS87415
#undef  CONFIG_BLK_DEV_OPTI621
#undef  CONFIG_BLK_DEV_PDC202XX_OLD
#define CONFIG_BLK_DEV_PDC202XX_OLD_MODULE 1
#define CONFIG_PDC202XX_BURST 1
#undef  CONFIG_BLK_DEV_PDC202XX_NEW
#undef  CONFIG_PDC202XX_FORCE
#undef  CONFIG_BLK_DEV_RZ1000
#undef  CONFIG_BLK_DEV_SC1200
#undef  CONFIG_BLK_DEV_SVWKS
#undef  CONFIG_BLK_DEV_SIIMAGE
#undef  CONFIG_BLK_DEV_SIS5513
#undef  CONFIG_BLK_DEV_SLC90E66
#undef  CONFIG_BLK_DEV_TRM290
#undef  CONFIG_BLK_DEV_VIA82CXXX
#undef  CONFIG_IDE_CHIPSETS
#define CONFIG_IDEDMA_AUTO 1
#define CONFIG_IDEDMA_IVB 1
#undef  CONFIG_DMA_NONPCI
#define CONFIG_BLK_DEV_PDC202XX 1
#undef  CONFIG_BLK_DEV_ATARAID
#undef  CONFIG_BLK_DEV_ATARAID_PDC
#undef  CONFIG_BLK_DEV_ATARAID_HPT
#undef  CONFIG_BLK_DEV_ATARAID_MEDLEY
#undef  CONFIG_BLK_DEV_ATARAID_SII

/*
 * SCSI support
 */
#undef  CONFIG_SCSI
#define CONFIG_SCSI_MODULE 1

/*
 * SCSI support type (disk, tape, CD-ROM)
 */
#undef  CONFIG_BLK_DEV_SD
#define CONFIG_BLK_DEV_SD_MODULE 1
#define CONFIG_SD_EXTRA_DEVS (5)
#undef  CONFIG_CHR_DEV_ST
#undef  CONFIG_CHR_DEV_OSST
#undef  CONFIG_BLK_DEV_SR
#undef  CONFIG_CHR_DEV_SG
#define CONFIG_CHR_DEV_SG_MODULE 1

/*
 * Some SCSI devices (e.g. CD jukebox) support multiple LUNs
 */
#undef  CONFIG_SCSI_DEBUG_QUEUES
#define CONFIG_SCSI_MULTI_LUN 1
#undef  CONFIG_SCSI_CONSTANTS
#undef  CONFIG_SCSI_LOGGING

/*
 * SCSI low-level drivers
 */
#undef  CONFIG_BLK_DEV_3W_XXXX_RAID
#undef  CONFIG_SCSI_7000FASST
#undef  CONFIG_SCSI_ACARD
#undef  CONFIG_SCSI_AHA152X
#undef  CONFIG_SCSI_AHA1542
#undef  CONFIG_SCSI_AHA1740
#undef  CONFIG_SCSI_AACRAID
#undef  CONFIG_SCSI_AIC7XXX
#undef  CONFIG_SCSI_AIC79XX
#undef  CONFIG_SCSI_AIC7XXX_OLD
#undef  CONFIG_SCSI_DPT_I2O
#undef  CONFIG_SCSI_ADVANSYS
#undef  CONFIG_SCSI_IN2000
#undef  CONFIG_SCSI_AM53C974
#undef  CONFIG_SCSI_MEGARAID
#undef  CONFIG_SCSI_MEGARAID2
#undef  CONFIG_SCSI_SATA
#undef  CONFIG_SCSI_SATA_AHCI
#undef  CONFIG_SCSI_SATA_SVW
#undef  CONFIG_SCSI_ATA_PIIX
#undef  CONFIG_SCSI_SATA_NV
#undef  CONFIG_SCSI_SATA_QSTOR
#undef  CONFIG_SCSI_SATA_PROMISE
#undef  CONFIG_SCSI_SATA_SX4
#undef  CONFIG_SCSI_SATA_SIL
#undef  CONFIG_SCSI_SATA_SIS
#undef  CONFIG_SCSI_SATA_ULI
#undef  CONFIG_SCSI_SATA_VIA
#undef  CONFIG_SCSI_SATA_VITESSE
#undef  CONFIG_SCSI_BUSLOGIC
#undef  CONFIG_SCSI_CPQFCTS
#undef  CONFIG_SCSI_DMX3191D
#undef  CONFIG_SCSI_DTC3280
#undef  CONFIG_SCSI_EATA
#undef  CONFIG_SCSI_EATA_DMA
#undef  CONFIG_SCSI_EATA_PIO
#undef  CONFIG_SCSI_FUTURE_DOMAIN
#undef  CONFIG_SCSI_GDTH
#undef  CONFIG_SCSI_GENERIC_NCR5380
#undef  CONFIG_SCSI_INITIO
#undef  CONFIG_SCSI_INIA100
#undef  CONFIG_SCSI_PPA
#undef  CONFIG_SCSI_IMM
#undef  CONFIG_SCSI_NCR53C406A
#undef  CONFIG_SCSI_NCR53C7xx
#undef  CONFIG_SCSI_SYM53C8XX_2
#undef  CONFIG_SCSI_NCR53C8XX
#undef  CONFIG_SCSI_SYM53C8XX
#undef  CONFIG_SCSI_PAS16
#undef  CONFIG_SCSI_PCI2000
#undef  CONFIG_SCSI_PCI2220I
#undef  CONFIG_SCSI_PSI240I
#undef  CONFIG_SCSI_QLOGIC_FAS
#undef  CONFIG_SCSI_QLOGIC_ISP
#undef  CONFIG_SCSI_QLOGIC_FC
#undef  CONFIG_SCSI_QLOGIC_1280
#undef  CONFIG_SCSI_SIM710
#undef  CONFIG_SCSI_SYM53C416
#undef  CONFIG_SCSI_DC390T
#undef  CONFIG_SCSI_T128
#undef  CONFIG_SCSI_U14_34F
#undef  CONFIG_SCSI_NSP32
#undef  CONFIG_SCSI_DEBUG

/*
 * PCMCIA SCSI adapter support
 */
#undef  CONFIG_SCSI_PCMCIA

/*
 * Fusion MPT device support
 */
#undef  CONFIG_FUSION
#undef  CONFIG_FUSION_BOOT
#undef  CONFIG_FUSION_ISENSE
#undef  CONFIG_FUSION_CTL
#undef  CONFIG_FUSION_LAN

/*
 * IEEE 1394 (FireWire) support (EXPERIMENTAL)
 */
#undef  CONFIG_IEEE1394

/*
 * I2O device support
 */
#undef  CONFIG_I2O
#undef  CONFIG_I2O_PCI
#undef  CONFIG_I2O_BLOCK
#undef  CONFIG_I2O_LAN
#undef  CONFIG_I2O_SCSI
#undef  CONFIG_I2O_PROC

/*
 * Network device support
 */
#define CONFIG_NETDEVICES 1
#define CONFIG_HND 1

/*
 * ARCnet devices
 */
#undef  CONFIG_ARCNET
#undef  CONFIG_DUMMY
#undef  CONFIG_BONDING
#undef  CONFIG_EQUALIZER
#undef  CONFIG_IMQ
#define CONFIG_IMQ_MODULE 1
#undef  CONFIG_TUN
#define CONFIG_TUN_MODULE 1
#define CONFIG_NET_RANDOM 1
#undef  CONFIG_ETHERTAP

/*
 * Ethernet (10 or 100Mbit)
 */
#define CONFIG_NET_ETHERNET 1
#undef  CONFIG_SUNLANCE
#undef  CONFIG_HAPPYMEAL
#undef  CONFIG_SUNBMAC
#undef  CONFIG_SUNQE
#undef  CONFIG_SUNGEM
#undef  CONFIG_NET_VENDOR_3COM
#undef  CONFIG_LANCE
#undef  CONFIG_NET_VENDOR_SMC
#undef  CONFIG_NET_VENDOR_RACAL
#undef  CONFIG_HP100
#undef  CONFIG_NET_ISA
#define CONFIG_NET_PCI 1
#undef  CONFIG_PCNET32
#undef  CONFIG_AMD8111_ETH
#undef  CONFIG_ADAPTEC_STARFIRE
#undef  CONFIG_APRICOT
#define CONFIG_B44 1
#undef  CONFIG_CS89x0
#undef  CONFIG_TULIP
#undef  CONFIG_DE4X5
#undef  CONFIG_DGRS
#undef  CONFIG_DM9102
#undef  CONFIG_EEPRO100
#undef  CONFIG_EEPRO100_PIO
#undef  CONFIG_E100
#undef  CONFIG_LNE390
#undef  CONFIG_FEALNX
#undef  CONFIG_NATSEMI
#undef  CONFIG_NE2K_PCI
#undef  CONFIG_FORCEDETH
#undef  CONFIG_NE3210
#undef  CONFIG_ES3210
#undef  CONFIG_8139CP
#undef  CONFIG_8139TOO
#undef  CONFIG_8139TOO_PIO
#undef  CONFIG_8139TOO_TUNE_TWISTER
#undef  CONFIG_8139TOO_8129
#undef  CONFIG_8139_OLD_RX_RESET
#undef  CONFIG_SIS900
#undef  CONFIG_EPIC100
#undef  CONFIG_SUNDANCE
#undef  CONFIG_SUNDANCE_MMIO
#undef  CONFIG_TLAN
#undef  CONFIG_VIA_RHINE
#undef  CONFIG_VIA_RHINE_MMIO
#undef  CONFIG_WINBOND_840
#undef  CONFIG_LAN_SAA9730
#undef  CONFIG_NET_POCKET

/*
 * Ethernet (1000 Mbit)
 */
#undef  CONFIG_ACENIC
#undef  CONFIG_DL2K
#undef  CONFIG_E1000
#undef  CONFIG_MYRI_SBUS
#undef  CONFIG_NS83820
#undef  CONFIG_HAMACHI
#undef  CONFIG_YELLOWFIN
#undef  CONFIG_R8169
#undef  CONFIG_SK98LIN
#undef  CONFIG_TIGON3
#undef  CONFIG_FDDI
#undef  CONFIG_HIPPI
#undef  CONFIG_PLIP
#undef  CONFIG_PPP
#define CONFIG_PPP_MODULE 1
#undef  CONFIG_PPP_MULTILINK
#define CONFIG_PPP_FILTER 1
#undef  CONFIG_PPP_ASYNC
#define CONFIG_PPP_ASYNC_MODULE 1
#undef  CONFIG_PPP_SYNC_TTY
#undef  CONFIG_PPP_DEFLATE
#define CONFIG_PPP_DEFLATE_MODULE 1
#undef  CONFIG_PPP_BSDCOMP
#define CONFIG_PPP_BSDCOMP_MODULE 1
#undef  CONFIG_PPP_MPPE_MPPC
#define CONFIG_PPP_MPPE_MPPC_MODULE 1
#undef  CONFIG_PPPOE
#define CONFIG_PPPOE_MODULE 1
#undef  CONFIG_SLIP

/*
 * Wireless LAN (non-hamradio)
 */
#define CONFIG_NET_RADIO 1
#undef  CONFIG_STRIP
#undef  CONFIG_WAVELAN
#undef  CONFIG_ARLAN
#undef  CONFIG_AIRONET4500
#undef  CONFIG_AIRONET4500_NONCS
#undef  CONFIG_AIRONET4500_PROC
#undef  CONFIG_AIRO
#undef  CONFIG_HERMES
#undef  CONFIG_WL
#define CONFIG_WL_MODULE 1
#undef  CONFIG_PLX_HERMES
#undef  CONFIG_TMD_HERMES
#undef  CONFIG_PCI_HERMES

/*
 * Wireless Pcmcia cards support
 */
#undef  CONFIG_PCMCIA_HERMES
#undef  CONFIG_AIRO_CS
#undef  CONFIG_PCMCIA_ATMEL

/*
 * Prism54 PCI/PCMCIA GT/Duette Driver - 802.11(a/b/g)
 */
#undef  CONFIG_PRISM54
#define CONFIG_NET_WIRELESS 1

/*
 * Token Ring devices
 */
#undef  CONFIG_TR
#undef  CONFIG_NET_FC
#undef  CONFIG_RCPCI
#undef  CONFIG_SHAPER
#define CONFIG_SHAPER_MODULE 1

/*
 * Wan interfaces
 */
#undef  CONFIG_WAN

/*
 * PCMCIA network device support
 */
#undef  CONFIG_NET_PCMCIA

/*
 * Amateur Radio support
 */
#define CONFIG_HAMRADIO 1

/*
 * Packet Radio protocols
 */
#undef  CONFIG_AX25
#define CONFIG_AX25_MODULE 1
#undef  CONFIG_AX25_DAMA_SLAVE
#undef  CONFIG_NETROM
#undef  CONFIG_ROSE

/*
 * AX.25 network device drivers
 */

/*
 * AX.25 network device drivers
 */
#undef  CONFIG_MKISS
#define CONFIG_MKISS_MODULE 1
#undef  CONFIG_6PACK
#undef  CONFIG_BPQETHER
#undef  CONFIG_SCC_DELAY
#undef  CONFIG_SCC_TRXECHO
#undef  CONFIG_BAYCOM_SER_FDX
#undef  CONFIG_BAYCOM_SER_HDX
#undef  CONFIG_BAYCOM_PAR
#undef  CONFIG_BAYCOM_EPP
#undef  CONFIG_SOUNDMODEM
#undef  CONFIG_YAM

/*
 * IrDA (infrared) support
 */
#undef  CONFIG_IRDA

/*
 * ISDN subsystem
 */
#undef  CONFIG_ISDN

/*
 * Input core support
 */
#undef  CONFIG_INPUT
#undef  CONFIG_INPUT_KEYBDEV
#undef  CONFIG_INPUT_MOUSEDEV
#undef  CONFIG_INPUT_JOYDEV
#undef  CONFIG_INPUT_EVDEV
#undef  CONFIG_INPUT_UINPUT

/*
 * Character devices
 */
#undef  CONFIG_VT
#define CONFIG_SERIAL 1
#define CONFIG_SERIAL_CONSOLE 1
#undef  CONFIG_SERIAL_EXTENDED
#undef  CONFIG_SERIAL_NONSTANDARD
#define CONFIG_UNIX98_PTYS 1
#define CONFIG_UNIX98_PTY_COUNT (128)
#undef  CONFIG_PRINTER
#define CONFIG_PRINTER_MODULE 1
#undef  CONFIG_LP_CONSOLE
#undef  CONFIG_PPDEV
#define CONFIG_PPDEV_MODULE 1
#undef  CONFIG_TIPAR

/*
 * I2C support
 */
#undef  CONFIG_I2C

/*
 * Mice
 */
#undef  CONFIG_BUSMOUSE
#undef  CONFIG_MOUSE

/*
 * Joysticks
 */
#undef  CONFIG_INPUT_GAMEPORT

/*
 * Input core support is needed for gameports
 */

/*
 * Input core support is needed for joysticks
 */
#undef  CONFIG_QIC02_TAPE
#undef  CONFIG_IPMI_HANDLER
#undef  CONFIG_IPMI_PANIC_EVENT
#undef  CONFIG_IPMI_DEVICE_INTERFACE
#undef  CONFIG_IPMI_KCS
#undef  CONFIG_IPMI_WATCHDOG

/*
 * Watchdog Cards
 */
#define CONFIG_WATCHDOG 1
#define CONFIG_WATCHDOG_NOWAYOUT 1
#undef  CONFIG_ACQUIRE_WDT
#undef  CONFIG_ADVANTECH_WDT
#undef  CONFIG_ALIM1535_WDT
#undef  CONFIG_ALIM7101_WDT
#undef  CONFIG_SC520_WDT
#undef  CONFIG_PCWATCHDOG
#undef  CONFIG_EUROTECH_WDT
#undef  CONFIG_IB700_WDT
#undef  CONFIG_WAFER_WDT
#undef  CONFIG_I810_TCO
#undef  CONFIG_MIXCOMWD
#undef  CONFIG_60XX_WDT
#undef  CONFIG_SC1200_WDT
#undef  CONFIG_SCx200_WDT
#undef  CONFIG_SOFT_WATCHDOG
#define CONFIG_SOFT_WATCHDOG_MODULE 1
#undef  CONFIG_W83877F_WDT
#undef  CONFIG_WDT
#undef  CONFIG_WDTPCI
#undef  CONFIG_MACHZ_WDT
#undef  CONFIG_SCx200
#undef  CONFIG_SCx200_GPIO
#undef  CONFIG_AMD_PM768
#undef  CONFIG_NVRAM
#undef  CONFIG_RTC
#undef  CONFIG_DTLK
#undef  CONFIG_R3964
#undef  CONFIG_APPLICOM

/*
 * Ftape, the floppy tape device driver
 */
#undef  CONFIG_FTAPE
#undef  CONFIG_AGP

/*
 * Direct Rendering Manager (XFree86 DRI support)
 */
#undef  CONFIG_DRM

/*
 * PCMCIA character devices
 */
#undef  CONFIG_PCMCIA_SERIAL_CS
#define CONFIG_PCMCIA_SERIAL_CS_MODULE 1
#undef  CONFIG_SYNCLINK_CS

/*
 * File systems
 */
#undef  CONFIG_QUOTA
#undef  CONFIG_QFMT_V2
#undef  CONFIG_AUTOFS_FS
#undef  CONFIG_AUTOFS4_FS
#undef  CONFIG_REISERFS_FS
#undef  CONFIG_REISERFS_CHECK
#undef  CONFIG_REISERFS_PROC_INFO
#undef  CONFIG_ADFS_FS
#undef  CONFIG_ADFS_FS_RW
#undef  CONFIG_AFFS_FS
#undef  CONFIG_HFS_FS
#undef  CONFIG_HFSPLUS_FS
#define CONFIG_HFSPLUS_FS_MODULE 1
#undef  CONFIG_BEFS_FS
#undef  CONFIG_BEFS_DEBUG
#undef  CONFIG_BFS_FS
#undef  CONFIG_EXT3_FS
#define CONFIG_EXT3_FS_MODULE 1
#undef  CONFIG_JBD
#define CONFIG_JBD_MODULE 1
#undef  CONFIG_JBD_DEBUG
#undef  CONFIG_FAT_FS
#define CONFIG_FAT_FS_MODULE 1
#undef  CONFIG_MSDOS_FS
#undef  CONFIG_UMSDOS_FS
#undef  CONFIG_VFAT_FS
#define CONFIG_VFAT_FS_MODULE 1
#undef  CONFIG_EFS_FS
#undef  CONFIG_JFFS_FS
#define CONFIG_JFFS2_FS 1
#define CONFIG_JFFS2_FS_DEBUG (0)
#undef  CONFIG_JFFS2_BBC_ARMLIB
#undef  CONFIG_JFFS2_BBC_LZO
#define CONFIG_JFFS2_BBC_LZARI 1
#undef  CONFIG_JFFS2_BBC_LZHD
#undef  CONFIG_JFFS2_BBC_LZSS
#undef  CONFIG_CRAMFS
#define CONFIG_SQUASHFS 1
#undef  CONFIG_SQUASHFS_EMBEDDED
#define CONFIG_TMPFS 1
#define CONFIG_RAMFS 1
#undef  CONFIG_ISO9660_FS
#define CONFIG_ISO9660_FS_MODULE 1
#define CONFIG_JOLIET 1
#undef  CONFIG_ZISOFS
#undef  CONFIG_JFS_FS
#undef  CONFIG_JFS_DEBUG
#undef  CONFIG_JFS_STATISTICS
#undef  CONFIG_MINIX_FS
#define CONFIG_MINIX_FS_MODULE 1
#undef  CONFIG_VXFS_FS
#undef  CONFIG_NTFS_FS
#undef  CONFIG_NTFS_RW
#undef  CONFIG_HPFS_FS
#define CONFIG_PROC_FS 1
#define CONFIG_DEVFS_FS 1
#define CONFIG_DEVFS_MOUNT 1
#undef  CONFIG_DEVFS_DEBUG
#define CONFIG_DEVPTS_FS 1
#undef  CONFIG_QNX4FS_FS
#undef  CONFIG_QNX4FS_RW
#undef  CONFIG_ROMFS_FS
#undef  CONFIG_EXT2_FS
#define CONFIG_EXT2_FS_MODULE 1
#undef  CONFIG_SYSV_FS
#undef  CONFIG_UDF_FS
#undef  CONFIG_UDF_RW
#undef  CONFIG_UFS_FS
#undef  CONFIG_UFS_FS_WRITE
#undef  CONFIG_XFS_FS
#define CONFIG_XFS_FS_MODULE 1
#undef  CONFIG_XFS_QUOTA
#undef  CONFIG_XFS_RT
#undef  CONFIG_XFS_TRACE
#undef  CONFIG_XFS_DEBUG

/*
 * Network File Systems
 */
#undef  CONFIG_CODA_FS
#undef  CONFIG_INTERMEZZO_FS
#undef  CONFIG_NFS_FS
#define CONFIG_NFS_FS_MODULE 1
#define CONFIG_NFS_V3 1
#undef  CONFIG_NFS_DIRECTIO
#undef  CONFIG_ROOT_NFS
#undef  CONFIG_NFSD
#undef  CONFIG_NFSD_V3
#undef  CONFIG_NFSD_TCP
#undef  CONFIG_SUNRPC
#define CONFIG_SUNRPC_MODULE 1
#undef  CONFIG_LOCKD
#define CONFIG_LOCKD_MODULE 1
#define CONFIG_LOCKD_V4 1
#undef  CONFIG_CIFS
#define CONFIG_CIFS_MODULE 1
#undef  CONFIG_CIFS_STATS
#define CONFIG_CIFS_POSIX 1
#undef  CONFIG_SMB_FS
#undef  CONFIG_NCP_FS
#undef  CONFIG_NCPFS_PACKET_SIGNING
#undef  CONFIG_NCPFS_IOCTL_LOCKING
#undef  CONFIG_NCPFS_STRONG
#undef  CONFIG_NCPFS_NFS_NS
#undef  CONFIG_NCPFS_OS2_NS
#undef  CONFIG_NCPFS_SMALLDOS
#undef  CONFIG_NCPFS_NLS
#undef  CONFIG_NCPFS_EXTRAS
#undef  CONFIG_ZISOFS_FS

/*
 * Partition Types
 */
#define CONFIG_PARTITION_ADVANCED 1
#undef  CONFIG_ACORN_PARTITION
#undef  CONFIG_OSF_PARTITION
#undef  CONFIG_AMIGA_PARTITION
#undef  CONFIG_ATARI_PARTITION
#define CONFIG_MAC_PARTITION 1
#define CONFIG_MSDOS_PARTITION 1
#undef  CONFIG_BSD_DISKLABEL
#undef  CONFIG_MINIX_SUBPARTITION
#undef  CONFIG_SOLARIS_X86_PARTITION
#undef  CONFIG_UNIXWARE_DISKLABEL
#undef  CONFIG_LDM_PARTITION
#undef  CONFIG_SGI_PARTITION
#undef  CONFIG_ULTRIX_PARTITION
#undef  CONFIG_SUN_PARTITION
#undef  CONFIG_EFI_PARTITION
#undef  CONFIG_SMB_NLS
#define CONFIG_NLS 1

/*
 * Native Language Support
 */
#define CONFIG_NLS_DEFAULT "iso8859-1"
#undef  CONFIG_NLS_CODEPAGE_437
#undef  CONFIG_NLS_CODEPAGE_737
#undef  CONFIG_NLS_CODEPAGE_775
#undef  CONFIG_NLS_CODEPAGE_850
#undef  CONFIG_NLS_CODEPAGE_852
#undef  CONFIG_NLS_CODEPAGE_855
#undef  CONFIG_NLS_CODEPAGE_857
#undef  CONFIG_NLS_CODEPAGE_860
#undef  CONFIG_NLS_CODEPAGE_861
#undef  CONFIG_NLS_CODEPAGE_862
#undef  CONFIG_NLS_CODEPAGE_863
#undef  CONFIG_NLS_CODEPAGE_864
#undef  CONFIG_NLS_CODEPAGE_865
#undef  CONFIG_NLS_CODEPAGE_866
#undef  CONFIG_NLS_CODEPAGE_869
#undef  CONFIG_NLS_CODEPAGE_936
#undef  CONFIG_NLS_CODEPAGE_950
#undef  CONFIG_NLS_CODEPAGE_932
#undef  CONFIG_NLS_CODEPAGE_949
#undef  CONFIG_NLS_CODEPAGE_874
#undef  CONFIG_NLS_ISO8859_8
#undef  CONFIG_NLS_CODEPAGE_1250
#undef  CONFIG_NLS_CODEPAGE_1251
#undef  CONFIG_NLS_ISO8859_1
#undef  CONFIG_NLS_ISO8859_2
#undef  CONFIG_NLS_ISO8859_3
#undef  CONFIG_NLS_ISO8859_4
#undef  CONFIG_NLS_ISO8859_5
#undef  CONFIG_NLS_ISO8859_6
#undef  CONFIG_NLS_ISO8859_7
#undef  CONFIG_NLS_ISO8859_9
#undef  CONFIG_NLS_ISO8859_13
#undef  CONFIG_NLS_ISO8859_14
#undef  CONFIG_NLS_ISO8859_15
#undef  CONFIG_NLS_KOI8_R
#undef  CONFIG_NLS_KOI8_U
#undef  CONFIG_NLS_UTF8

/*
 * Multimedia devices
 */
#undef  CONFIG_VIDEO_DEV
#define CONFIG_VIDEO_DEV_MODULE 1

/*
 * Video For Linux
 */
#define CONFIG_VIDEO_PROC_FS 1
#undef  CONFIG_I2C_PARPORT

/*
 * Video Adapters
 */
#undef  CONFIG_VIDEO_BT848
#undef  CONFIG_VIDEO_PMS
#undef  CONFIG_VIDEO_BWQCAM
#undef  CONFIG_VIDEO_CQCAM
#undef  CONFIG_VIDEO_CPIA
#undef  CONFIG_VIDEO_SAA5249
#undef  CONFIG_TUNER_3036
#undef  CONFIG_VIDEO_STRADIS
#undef  CONFIG_VIDEO_ZORAN
#undef  CONFIG_VIDEO_ZORAN_BUZ
#undef  CONFIG_VIDEO_ZORAN_DC10
#undef  CONFIG_VIDEO_ZORAN_LML33
#undef  CONFIG_VIDEO_ZR36120
#undef  CONFIG_VIDEO_MEYE

/*
 * Radio Adapters
 */
#undef  CONFIG_RADIO_GEMTEK_PCI
#undef  CONFIG_RADIO_MAXIRADIO
#undef  CONFIG_RADIO_MAESTRO
#undef  CONFIG_RADIO_MIROPCM20

/*
 * Sound
 */
#undef  CONFIG_SOUND
#define CONFIG_SOUND_MODULE 1
#undef  CONFIG_SOUND_ALI5455
#undef  CONFIG_SOUND_BT878
#undef  CONFIG_SOUND_CMPCI
#undef  CONFIG_SOUND_EMU10K1
#undef  CONFIG_MIDI_EMU10K1
#undef  CONFIG_SOUND_FUSION
#undef  CONFIG_SOUND_CS4281
#undef  CONFIG_SOUND_ES1370
#undef  CONFIG_SOUND_ES1371
#undef  CONFIG_SOUND_ESSSOLO1
#undef  CONFIG_SOUND_MAESTRO
#undef  CONFIG_SOUND_MAESTRO3
#undef  CONFIG_SOUND_FORTE
#undef  CONFIG_SOUND_ICH
#undef  CONFIG_SOUND_RME96XX
#undef  CONFIG_SOUND_SONICVIBES
#undef  CONFIG_SOUND_TRIDENT
#undef  CONFIG_SOUND_MSNDCLAS
#undef  CONFIG_SOUND_MSNDPIN
#undef  CONFIG_SOUND_VIA82CXXX
#undef  CONFIG_MIDI_VIA82CXXX
#undef  CONFIG_SOUND_OSS
#undef  CONFIG_SOUND_TVMIXER
#undef  CONFIG_SOUND_AD1980
#undef  CONFIG_SOUND_WM97XX

/*
 * USB support
 */
#undef  CONFIG_USB
#define CONFIG_USB_MODULE 1
#undef  CONFIG_USB_DEBUG

/*
 * Miscellaneous USB options
 */
#define CONFIG_USB_DEVICEFS 1
#undef  CONFIG_USB_BANDWIDTH

/*
 * USB Host Controller Drivers
 */
#undef  CONFIG_USB_EHCI_HCD
#define CONFIG_USB_EHCI_HCD_MODULE 1
#undef  CONFIG_USB_UHCI
#undef  CONFIG_USB_UHCI_ALT
#define CONFIG_USB_UHCI_ALT_MODULE 1
#undef  CONFIG_USB_OHCI
#define CONFIG_USB_OHCI_MODULE 1

/*
 * USB Device Class drivers
 */
#undef  CONFIG_USB_AUDIO
#define CONFIG_USB_AUDIO_MODULE 1
#undef  CONFIG_USB_EMI26

/*
 *   USB Bluetooth can only be used with disabled Bluetooth subsystem
 */
#undef  CONFIG_USB_MIDI
#undef  CONFIG_USB_STORAGE
#define CONFIG_USB_STORAGE_MODULE 1
#undef  CONFIG_USB_STORAGE_DEBUG
#define CONFIG_USB_STORAGE_DATAFAB 1
#define CONFIG_USB_STORAGE_FREECOM 1
#undef  CONFIG_USB_STORAGE_ISD200
#define CONFIG_USB_STORAGE_DPCM 1
#define CONFIG_USB_STORAGE_HP8200e 1
#define CONFIG_USB_STORAGE_SDDR09 1
#define CONFIG_USB_STORAGE_SDDR55 1
#define CONFIG_USB_STORAGE_JUMPSHOT 1
#undef  CONFIG_USB_ACM
#define CONFIG_USB_ACM_MODULE 1
#undef  CONFIG_USB_PRINTER
#define CONFIG_USB_PRINTER_MODULE 1

/*
 * USB Human Interface Devices (HID)
 */
#undef  CONFIG_USB_HID

/*
 *     Input core support is needed for USB HID input layer or HIDBP support
 */
#undef  CONFIG_USB_HIDINPUT
#undef  CONFIG_USB_HIDDEV
#undef  CONFIG_USB_KBD
#undef  CONFIG_USB_MOUSE
#undef  CONFIG_USB_AIPTEK
#undef  CONFIG_USB_WACOM
#undef  CONFIG_USB_KBTAB
#undef  CONFIG_USB_POWERMATE

/*
 * USB Imaging devices
 */
#undef  CONFIG_USB_DC2XX
#undef  CONFIG_USB_MDC800
#undef  CONFIG_USB_SCANNER
#undef  CONFIG_USB_MICROTEK
#undef  CONFIG_USB_HPUSBSCSI

/*
 * USB Multimedia devices
 */
#undef  CONFIG_USB_IBMCAM
#undef  CONFIG_USB_KONICAWC
#undef  CONFIG_USB_OV511
#undef  CONFIG_USB_PWC
#define CONFIG_USB_PWC_MODULE 1
#undef  CONFIG_USB_SE401
#undef  CONFIG_USB_STV680
#undef  CONFIG_USB_W9968CF
#undef  CONFIG_USB_VICAM
#undef  CONFIG_USB_DSBR
#undef  CONFIG_USB_DABUSB

/*
 * USB Network adaptors
 */
#undef  CONFIG_USB_PEGASUS
#undef  CONFIG_USB_RTL8150
#undef  CONFIG_USB_KAWETH
#undef  CONFIG_USB_CATC
#undef  CONFIG_USB_CDCETHER
#undef  CONFIG_USB_USBNET

/*
 * USB port drivers
 */
#undef  CONFIG_USB_USS720

/*
 * USB Serial Converter support
 */
#undef  CONFIG_USB_SERIAL
#define CONFIG_USB_SERIAL_MODULE 1
#undef  CONFIG_USB_SERIAL_DEBUG
#define CONFIG_USB_SERIAL_GENERIC 1
#undef  CONFIG_USB_SERIAL_BELKIN
#define CONFIG_USB_SERIAL_BELKIN_MODULE 1
#undef  CONFIG_USB_SERIAL_WHITEHEAT
#undef  CONFIG_USB_SERIAL_DIGI_ACCELEPORT
#undef  CONFIG_USB_SERIAL_EMPEG
#undef  CONFIG_USB_SERIAL_FTDI_SIO
#define CONFIG_USB_SERIAL_FTDI_SIO_MODULE 1
#undef  CONFIG_USB_SERIAL_VISOR
#define CONFIG_USB_SERIAL_VISOR_MODULE 1
#undef  CONFIG_USB_SERIAL_IPAQ
#undef  CONFIG_USB_SERIAL_IR
#undef  CONFIG_USB_SERIAL_EDGEPORT
#undef  CONFIG_USB_SERIAL_EDGEPORT_TI
#undef  CONFIG_USB_SERIAL_KEYSPAN_PDA
#undef  CONFIG_USB_SERIAL_KEYSPAN
#undef  CONFIG_USB_SERIAL_MCT_U232
#define CONFIG_USB_SERIAL_MCT_U232_MODULE 1
#undef  CONFIG_USB_SERIAL_KLSI
#undef  CONFIG_USB_SERIAL_KOBIL_SCT
#undef  CONFIG_USB_SERIAL_PL2303
#define CONFIG_USB_SERIAL_PL2303_MODULE 1
#undef  CONFIG_USB_SERIAL_CYBERJACK
#undef  CONFIG_USB_SERIAL_XIRCOM
#undef  CONFIG_USB_SERIAL_OMNINET

/*
 * USB Miscellaneous drivers
 */
#undef  CONFIG_USB_RIO500
#undef  CONFIG_USB_AUERSWALD
#undef  CONFIG_USB_TIGL
#undef  CONFIG_USB_BRLVGER
#undef  CONFIG_USB_LCD

/*
 * Support for USB gadgets
 */
#undef  CONFIG_USB_GADGET

/*
 * Bluetooth support
 */
#undef  CONFIG_BLUEZ
#define CONFIG_BLUEZ_MODULE 1
#undef  CONFIG_BLUEZ_L2CAP
#define CONFIG_BLUEZ_L2CAP_MODULE 1
#undef  CONFIG_BLUEZ_SCO
#define CONFIG_BLUEZ_SCO_MODULE 1
#undef  CONFIG_BLUEZ_RFCOMM
#define CONFIG_BLUEZ_RFCOMM_MODULE 1
#define CONFIG_BLUEZ_RFCOMM_TTY 1
#undef  CONFIG_BLUEZ_BNEP
#define CONFIG_BLUEZ_BNEP_MODULE 1
#define CONFIG_BLUEZ_BNEP_MC_FILTER 1
#define CONFIG_BLUEZ_BNEP_PROTO_FILTER 1

/*
 * Bluetooth device drivers
 */
#undef  CONFIG_BLUEZ_HCIUSB
#define CONFIG_BLUEZ_HCIUSB_MODULE 1
#define CONFIG_BLUEZ_HCIUSB_SCO 1
#undef  CONFIG_BLUEZ_HCIUART
#define CONFIG_BLUEZ_HCIUART_MODULE 1
#define CONFIG_BLUEZ_HCIUART_H4 1
#define CONFIG_BLUEZ_HCIUART_BCSP 1
#define CONFIG_BLUEZ_HCIUART_BCSP_TXCRC 1
#undef  CONFIG_BLUEZ_HCIBFUSB
#undef  CONFIG_BLUEZ_HCIDTL1
#undef  CONFIG_BLUEZ_HCIBT3C
#undef  CONFIG_BLUEZ_HCIBLUECARD
#undef  CONFIG_BLUEZ_HCIBTUART
#undef  CONFIG_BLUEZ_HCIVHCI

/*
 * Kernel hacking
 */
#define CONFIG_CROSSCOMPILE 1
#undef  CONFIG_RUNTIME_DEBUG
#undef  CONFIG_REMOTE_DEBUG
#undef  CONFIG_GDB_CONSOLE
#undef  CONFIG_DEBUG_INFO
#define CONFIG_MAGIC_SYSRQ 1
#undef  CONFIG_MIPS_UNCACHED
#define CONFIG_LOG_BUF_SHIFT (0)

/*
 * Cryptographic options
 */
#define CONFIG_CRYPTO 1
#define CONFIG_CRYPTO_HMAC 1
#undef  CONFIG_CRYPTO_NULL
#undef  CONFIG_CRYPTO_MD4
#undef  CONFIG_CRYPTO_MD5
#define CONFIG_CRYPTO_MD5_MODULE 1
#undef  CONFIG_CRYPTO_SHA1
#define CONFIG_CRYPTO_SHA1_MODULE 1
#undef  CONFIG_CRYPTO_SHA256
#undef  CONFIG_CRYPTO_SHA512
#undef  CONFIG_CRYPTO_WP512
#undef  CONFIG_CRYPTO_DES
#define CONFIG_CRYPTO_DES_MODULE 1
#undef  CONFIG_CRYPTO_BLOWFISH
#undef  CONFIG_CRYPTO_TWOFISH
#undef  CONFIG_CRYPTO_SERPENT
#undef  CONFIG_CRYPTO_AES
#define CONFIG_CRYPTO_AES_MODULE 1
#undef  CONFIG_CRYPTO_CAST5
#undef  CONFIG_CRYPTO_CAST6
#undef  CONFIG_CRYPTO_TEA
#undef  CONFIG_CRYPTO_KHAZAD
#undef  CONFIG_CRYPTO_ANUBIS
#undef  CONFIG_CRYPTO_ARC4
#define CONFIG_CRYPTO_ARC4_MODULE 1
#undef  CONFIG_CRYPTO_DEFLATE
#define CONFIG_CRYPTO_DEFLATE_MODULE 1
#undef  CONFIG_CRYPTO_MICHAEL_MIC
#define CONFIG_CRYPTO_MICHAEL_MIC_MODULE 1
#undef  CONFIG_CRYPTO_TEST

/*
 * Library routines
 */
#undef  CONFIG_CRC32
#define CONFIG_ZLIB_INFLATE 1
#define CONFIG_ZLIB_DEFLATE 1
#undef  CONFIG_FW_LOADER
