#!/bin/sh

#exit 0

NAME=ser2net
PROG=/usr/sbin/$NAME

case "$1" in
start)
	$PROG -c /etc/ser2net.conf
	;;
stop)
	killall $NAME
        ;;
*)
	echo "Usage: $0 {start|stop}" >&2
        exit 1
        ;;
esac
                                          
exit $?
                                          

