/**********************************************************************************
;   Auto generated by target/linux/linux-2.4/adm5120.mk
;   DO NOT EDIT!!!
;**********************************************************************************/
#define FLASH_SIZE      0x00200000
#define FLASH_PART_BOOT_ADDR    0x00000000
#define FLASH_PART_BOOT_SIZE    0x00008000
#define FLASH_PART_KERNEL_ADDR  0x00010000
#define FLASH_PART_KERNEL_SIZE  0x000A0000
#define FLASH_PART_ROOT_SIZE    0x00140000
