#!/bin/sh

tun_dev=$1
tun_mtu=$2
link_mtu=$3
ifconfig_local_ip=$4
ifconfig_remote_ip=$5

logger -t openvpn_up "Connected client on $tun_dev, tun_mtu: $tun_mtu, link_mtu: $link_mtu, $ifconfig_local_ip:$ifconfig_remote_ip"
exit 0
