#!/bin/sh

# Write bluetooth PIN number here:
pin=1111

if [ -z "$pin" ]; then
	msg="Set bluetooth PIN in file $0"
	logger -p user.err "$msg"
	for i in /dev/pts/* ; do
		[ -w $i ] && echo "$msg" > $i
	done
else
	echo "PIN:$pin"
fi
