#!/bin/sh
#
# Starts opendchub.
#

test -x /usr/sbin/opendchub || exit 0
test -d /etc/.opendchub || exit 0

umask 077

start() {
 	echo -n "Starting opendchub: "
	start-stop-daemon --start --quiet --pidfile /var/run/opendchub.pid --exec /usr/sbin/opendchub -- -w /etc
	echo "OK"
}
stop() {
	echo -n "Stopping opendchub: "
	start-stop-daemon --stop --quiet --pidfile /var/run/opendchub.pid
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

