#!/bin/sh
#
# Starts pptpd.


test -r /etc/ppp/options || exit 0
test -x /usr/sbin/pppd || exit 0
test -x /usr/sbin/pptpd || exit 0

start() {
 	echo -n "Starting pptpd: "
	start-stop-daemon --start --quiet --pidfile /var/run/pptpd.pid --exec /usr/sbin/pptpd
	echo "OK"
}
stop() {
	echo -n "Stopping pptpd: "
	start-stop-daemon --stop --quiet --pidfile /var/run/pptpd.pid
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

